[package]
name = "to_do"
version = "0.1.0"
authors = ["hexcowboy <hex@cowboy.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
